image: registry.gitlab.com/pages/hugo:latest

stages:
  - build
  - production

buildHugo:
  stage: build
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master

production:
  image: python:latest
  stage: deploy
  dependencies:
    - buildHugo
  before_script:
    - pip install awscli
  script:
    - aws s3 cp public/ s3://$BUCKET_NAME/ --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://$BUCKET_NAME.s3-website-us-east-1.amazonaws.com/  # This is the url of the bucket we saved before
    on_stop: clean_s3 # When the branch is merged, we clean up after ourself

clean_s3:
  image: python:latest
  stage: production
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://$BUCKET_NAME/ --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    action: stop
  when: manual