# Site settings
baseurl = "https://david-coy.com/"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "en"
title = "{ David Coy }"
theme = "cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-83205152-2"
hasCJKLanguage = false
pygmentsStyle = "lovelace"
pygmentsCodefences = true

[params]
	name = "David Coy"
	description = "Blogger | Software Development | Coffee"
	bio = "Blogger | Software Development | Coffee"
	
	twitter = "obsidianspork"
	enableRSS = false
	enableToc = true

	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = false

	# Disable duoshuo comments by set `enableDuoshuo = "false"`
	enableDuoshuo = false

	enableGithubIssuesTips = false

	# Enable googleAnalytics
	enableGoogleAnalytics = true

	enableBaiduAnalytics = false

	# Add custom assets with their paths relative to the static folder
	customCSS = ["css/customCSS.css"]
	# customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = "About"
	archive = "Blog"
	subscribe = ""
	tags = ""

	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""

	# Sharing options and author information in posts
	aboutAuthor = "Blogger. Software Development and Coffee"
	tweet = "Blogger. Software Development and Coffee"
	share = "Blogger. Software Development and Coffee"

	# 404 page	
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = ""


# Add additional social link entries underneath
[social]
  twitter  = "https://twitter.com/obsidianspork"
  linkedin = "https://linkedin.com/in/david-coy"
  github   = "https://github.com/obsidianspork"
	gitlab   = "https://gitlab.com/obsidianspork"
